config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'user_management', to: 'user_management#index'
  get 'user_management/edit/:id', to: 'user_management#edit', as: :user
  patch 'user_management/edit/:id', to: 'user_management#create'
  resources :price_for_advantages
  resources :price_for_reservations
  resources :price_advantages
  resources :reservations
  resources :halls
  resources :time_ranges
  devise_for :users
  get 'home/index'
  root 'home#index'
  get 'halls/:id/reservations', to: 'halls#reservation_form'
  post 'halls/:id/reservations', to: 'halls#reservations'
  get 'my_reservations', to: 'reservations#my_reservations'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/price_for_reservation.rb
# frozen_string_literal: true

# This class represents a price specification for given combination of a time range and
# a hall. It validates the given information (for example from the form) and it checks
# whether price for the given hall is not defined for the given time range. It is used
# also for counting the price of a reservation.
class PriceForReservation < ApplicationRecord
  has_many :price_for_advantages, dependent: :destroy

  belongs_to :hall
  belongs_to :time_range

  validates :price, presence: true
  validate :positive_price
  validate :no_overlap_for_hall

  def positive_price
    return if price.nil?

    errors.add(:price, :error) unless price.positive?
  end

  def overlap_for_hall
    prices_for_reservation = PriceForReservation.where(hall_id: hall_id)
    overlap = 0
    prices_for_reservation.each do |price_for_reservation|
      hours = price_for_reservation.hours_in_time_range(time_range.from, time_range.to)
      overlap = 1 if hours.positive?
    end
    overlap
  end

  def possible_overlap_for_hall(from, to, time_range_id)
    prices_for_reservation = PriceForReservation.where(hall_id: hall_id)
    overlap = 0
    prices_for_reservation.each do |price_for_reservation|
      next if price_for_reservation.id == time_range_id

      hours = price_for_reservation.hours_in_time_range(from, to)
      overlap = 1 if hours.positive?
    end
    overlap
  end

  def no_overlap_for_hall
    errors.add(:time_range, :error) if overlap_for_hall.positive?
  end

  def get_price_after_discount(price, user)
    return price if user.price_advantage.nil?

    prices_for_advantage = PriceForAdvantage.where(price_for_reservation_id: id)
    price_for_advantage_for_user = prices_for_advantage.where(price_advantage: user.price_advantage)
    price_after_discount = price
    price_for_advantage_for_user.each do |price_for_user|
      price_after_discount = price_for_user.price_after_discount(price)
    end
    price_after_discount
  end

  def time_in_time_range(from, to)
    from_in_interval = from < time_range.from ? time_range.from : from
    to_in_interval = to > time_range.to ? time_range.to : to
    to_in_interval - from_in_interval
  end

  def hours_in_time_range(from, to)
    return 0 if to <= time_range.from || from >= time_range.to

    time_in_time_range(from, to) / 3600
  end

  def price_in_time_range(from, to, user)
    return 0 if to < time_range.from || from > time_range.to

    original_price = price * time_in_time_range(from, to) / 3600
    get_price_after_discount(original_price, user)
  end
end

app/controllers/price_for_reservations_controller.rb
# frozen_string_literal: true

# This class is a controller for management of price specifications for 
# a given combination of a hall and a time range.
class PriceForReservationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_price_for_reservation, only: %i[show edit update destroy]
  before_action :set_hall_array, only: %i[new edit create update]
  before_action :set_time_range_array, only: %i[new edit create update]

  # GET /price_for_reservations
  # GET /price_for_reservations.json
  def index
    @price_for_reservations = PriceForReservation.all
  end

  # GET /price_for_reservations/1
  # GET /price_for_reservations/1.json
  def show; end

  # GET /price_for_reservations/new
  def new
    @price_for_reservation = PriceForReservation.new
  end

  # GET /price_for_reservations/1/edit
  def edit; end

  # POST /price_for_reservations
  # POST /price_for_reservations.json
  def create
    @price_for_reservation = PriceForReservation.new(price_for_reservation_params)

    respond_to do |format|
      if @price_for_reservation.save
        notice = 'Price for reservation was successfully created.'
        format.html { redirect_to @price_for_reservation, notice: notice }
        format.json { render :show, status: :created, location: @price_for_reservation }
      else
        format.html { render :new }
        format.json { render json: @price_for_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_for_reservations/1
  # PATCH/PUT /price_for_reservations/1.json
  def update
    respond_to do |format|
      if @price_for_reservation.update(price_for_reservation_params)
        notice = 'Price for reservation was successfully updated.'
        format.html { redirect_to @price_for_reservation, notice: notice }
        format.json { render :show, status: :ok, location: @price_for_reservation }
      else
        format.html { render :edit }
        format.json { render json: @price_for_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_for_reservations/1
  # DELETE /price_for_reservations/1.json
  def destroy
    @price_for_reservation.destroy
    respond_to do |format|
      notice = 'Price for reservation was successfully destroyed.'
      format.html { redirect_to price_for_reservations_url, notice: notice }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_price_for_reservation
    @price_for_reservation = PriceForReservation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def price_for_reservation_params
    params.require(:price_for_reservation).permit(:price, :hall_id, :time_range_id)
  end

  def set_hall_array
    @halls = Hall.all
    @hall_array = []
    @halls.each do |hall|
      @hall_array.push([hall.title, hall.id])
    end
  end

  def set_time_range_array
    @time_ranges = TimeRange.all
    @time_range_array = []
    @time_ranges.each do |time_range|
      from = helpers.format_time(time_range.from)
      to = helpers.format_time(time_range.to)
      @time_range_array.push(["#{from} - #{to}", time_range.id])
    end
  end
end

app/helpers/price_for_reservations_helper.rb
# frozen_string_literal: true

# This helper is used for getting the string with the information about
# the price specification given by the identificator.
module PriceForReservationsHelper
  def info_of_price_for_reservation(id)
    price_specification = PriceForReservation.find(id)
    hall = Hall.find(price_specification.hall_id)
    time_range_to_string = time_range_string(price_specification.time_range_id)

    "#{price_specification.price} CZK/hour, #{hall.title} for time range #{time_range_to_string}"
  end
end

app/views/price_for_reservations/_form.html.erb
<p>All information are required.</p>

<%= form_with(model: price_for_reservation, local: true, :html => {:class => 'form-horizontal'}) do |form| %>
  <% if price_for_reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price_for_reservation.errors.count, "error") %> prohibited this price_for_reservation from being saved:</h2>

      <ul>
        <% price_for_reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :hall_id %>
    <%= form.select(:hall_id, @hall_array, {}, {class: 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.label :time_range_id %>
    <%= form.select(:time_range_id, @time_range_array, {}, {class: 'form-control'}) %>
  </div>

  <div class="form-group ml-auto text-right">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/price_for_reservations/edit.html.erb
<ul class="breadcrumb">
    <li class="breadcrumb-item">
        <%= link_to 'Home', root_path %>
    </li>
    <li class="breadcrumb-item">
        <%= link_to 'Price specifications', price_for_reservations_path %>
    </li>
    <li class="breadcrumb-item">Editing Price specification</li>
</ul>

<h1>Editing Price specification</h1>

<%= render 'form', price_for_reservation: @price_for_reservation %>

<div class="ml-auto mr-4 text-right">
    <%= link_to 'Show', @price_for_reservation, :class => 'btn btn-xs btn-default' %> |
    <%= link_to 'Back', price_for_reservations_path, :class => 'btn btn-xs btn-warning' %>
</div>

app/views/price_for_reservations/index.html.erb
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to 'Home', root_path %>
  </li>
  <li class="breadcrumb-item">Price specifications</li>
</ul>

<p id="notice"><%= notice %></p>

<h1>Price specifications</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Price</th>
      <th>Hall</th>
      <th>Time Range</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @price_for_reservations.each do |price_for_reservation| %>
      <tr>
        <td><%= price_for_reservation.price %></td>
        <td><%= link_to title_of_hall(price_for_reservation.hall_id), Hall.find(price_for_reservation.hall_id) %></td>
        <td><%= time_range_string(price_for_reservation.time_range_id) %></td>
        <td><%= link_to 'Show', price_for_reservation, :class => 'btn btn-xs btn-info' %>
        <%= link_to 'Edit', edit_price_for_reservation_path(price_for_reservation), :class => 'btn btn-xs btn-default' %>
        <%= link_to 'Destroy', price_for_reservation, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="ml-auto mr-4 text-right">
  <%= link_to 'New Price For Reservation', new_price_for_reservation_path, :class => 'btn btn-primary' %>
</div>

app/views/price_for_reservations/new.html.erb
<ul class="breadcrumb">
    <li class="breadcrumb-item">
        <%= link_to 'Home', root_path %>
    </li>
    <li class="breadcrumb-item">
        <%= link_to 'Price specifications', price_for_reservations_path %>
    </li>
    <li class="breadcrumb-item">New Price specification</li>
</ul>

<h1>New Price specification</h1>

<%= render 'form', price_for_reservation: @price_for_reservation %>

<div class="ml-auto mr-4 text-right">
    <%= link_to 'Back', price_for_reservations_path, :class => 'btn btn-xs btn-warning' %>
</div>

app/views/price_for_reservations/show.html.erb
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to 'Home', root_path %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to 'Price specifications', price_for_reservations_path %>
  </li>
  <li class="breadcrumb-item">Price specification detail</li>
</ul>

<p id="notice"><%= notice %></p>

<h1>Price specification detail</h1>

<p>
  <strong>Price:</strong>
  <%= @price_for_reservation.price %>
</p>

<p>
  <strong>Hall:</strong>
  <%= link_to title_of_hall(@price_for_reservation.hall_id), Hall.find(@price_for_reservation.hall_id) %>
</p>

<p>
  <strong>Time range:</strong>
  <%= time_range_string(@price_for_reservation.time_range_id) %>
</p>

<div class="ml-auto mr-4 text-right">
  <%= link_to 'Edit', edit_price_for_reservation_path(@price_for_reservation), :class => 'btn btn-xs btn-default' %> |
  <%= link_to 'Back', price_for_reservations_path, :class => 'btn btn-xs btn-warning' %>
</div>