config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'user_management', to: 'user_management#index'
  get 'user_management/edit/:id', to: 'user_management#edit', as: :user
  patch 'user_management/edit/:id', to: 'user_management#create'
  resources :price_for_advantages
  resources :price_for_reservations
  resources :price_advantages
  resources :reservations
  resources :halls
  resources :time_ranges
  devise_for :users
  get 'home/index'
  root 'home#index'
  get 'halls/:id/reservations', to: 'halls#reservation_form'
  post 'halls/:id/reservations', to: 'halls#reservations'
  get 'my_reservations', to: 'reservations#my_reservations'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/time_range.rb
# frozen_string_literal: true

# This class represents a time range and it checks the given information
# (for example from the form). It is used also during the check whether
# the hour price for reservation was not defined for the given hall and
# time range.
class TimeRange < ApplicationRecord
  has_many :price_for_reservations, dependent: :destroy

  validates :from, presence: true
  validates :to, presence: true
  validate :correct_time_range
  validate :no_overlap_for_any_hall

  def correct_time_range
    return if from.nil? || to.nil?

    errors.add(:from, :error) unless from < to
    errors.add(:to, :error) unless from < to
  end

  def no_overlap_for_any_hall
    overlap = 0
    price_for_reservations.each do |price_for_reservation|
      if price_for_reservation.possible_overlap_for_hall(from, to, id).positive?
        overlap = 1
        break
      end
    end
    errors.add(:from, :error) if overlap.positive?
    errors.add(:to, :error) if overlap.positive?
  end
end

app/controllers/time_ranges_controller.rb
# frozen_string_literal: true

# This class is a controller for management of time ranges. 
class TimeRangesController < ApplicationController
  load_and_authorize_resource
  before_action :set_time_range, only: %i[show edit update destroy]

  # GET /time_ranges
  # GET /time_ranges.json
  def index
    @time_ranges = TimeRange.all
  end

  # GET /time_ranges/1
  # GET /time_ranges/1.json
  def show; end

  # GET /time_ranges/new
  def new
    @time_range = TimeRange.new
  end

  # GET /time_ranges/1/edit
  def edit; end

  # POST /time_ranges
  # POST /time_ranges.json
  def create
    @time_range = TimeRange.new(time_range_params)

    respond_to do |format|
      if @time_range.save
        format.html { redirect_to @time_range, notice: 'Time range was successfully created.' }
        format.json { render :show, status: :created, location: @time_range }
      else
        format.html { render :new }
        format.json { render json: @time_range.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_ranges/1
  # PATCH/PUT /time_ranges/1.json
  def update
    respond_to do |format|
      if @time_range.update(time_range_params)
        format.html { redirect_to @time_range, notice: 'Time range was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_range }
      else
        format.html { render :edit }
        format.json { render json: @time_range.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_ranges/1
  # DELETE /time_ranges/1.json
  def destroy
    @time_range.destroy
    respond_to do |format|
      format.html { redirect_to time_ranges_url, notice: 'Time range was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_time_range
    @time_range = TimeRange.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def time_range_params
    params.require(:time_range).permit(:from, :to)
  end
end

app/helpers/time_ranges_helper.rb
# frozen_string_literal: true

# This helper is used for getting the string for the given identificator of a time range.
module TimeRangesHelper
  def time_range_string(id)
    time_range = TimeRange.find(id)
    "#{format_time(time_range.from)} - #{format_time(time_range.to)}"
  end
end

app/views/time_ranges/_form.html.erb
<p>All information are required.</p>

<%= form_with(model: time_range, local: true, :html => {:class => 'form-horizontal'}) do |form| %>
  <% if time_range.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_range.errors.count, "error") %> prohibited this time_range from being saved:</h2>

      <ul>
        <% time_range.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :from %>
    <%= form.time_select :from %>
  </div>

  <div class="form-group">
    <%= form.label :to %>
    <%= form.time_select :to %>
  </div>

  <div class="form-group ml-auto text-right" style="margin-right: 1.5 em">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/time_ranges/edit.html.erb
<ul class="breadcrumb">
    <li class="breadcrumb-item">
        <%= link_to 'Home', root_path %>
    </li>
    <li class="breadcrumb-item">
        <%= link_to 'Time ranges', time_ranges_path %>
    </li>
    <li class="breadcrumb-item">Editing Time Range</li>
</ul>

<h1>Editing Time Range</h1>

<%= render 'form', time_range: @time_range %>

<div class="ml-auto mr-4 text-right">
    <%= link_to 'Show', @time_range, :class => 'btn btn-xs btn-info' %> |
    <%= link_to 'Back', time_ranges_path, :class => 'btn btn-xs btn-warning' %>
</div>

app/views/time_ranges/index.html.erb
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to 'Home', root_path %>
  </li>
  <li class="breadcrumb-item">Time ranges</li>
</ul>

<p id="notice"><%= notice %></p>

<h1>Time Ranges</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Time range</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @time_ranges.each do |time_range| %>
      <tr>
        <td><%= format_time(time_range.from) %> - 
        <%= format_time(time_range.to) %></td>
        <td><%= link_to 'Show', time_range, :class => 'btn btn-xs btn-info' %>
        <%= link_to 'Edit', edit_time_range_path(time_range), :class => 'btn btn-xs btn-default' %>
        <%= link_to 'Destroy', time_range, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="ml-auto mr-4 text-right">
  <%= link_to 'New Time Range', new_time_range_path, :class => 'btn btn-primary' %>
</div>

app/views/time_ranges/new.html.erb
<h1>New Time Range</h1>

<%= render 'form', time_range: @time_range %>

<div class="ml-auto mr-4 text-right">
    <%= link_to 'Back', time_ranges_path, :class => 'btn btn-xs btn-warning' %>
</div>

app/views/time_ranges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= format_time(@time_range.from) %>
</p>

<p>
  <strong>To:</strong>
  <%= format_time(@time_range.to) %>
</p>

<div class="ml-auto mr-4 text-right">
  <%= link_to 'Edit', edit_time_range_path(@time_range), :class => 'btn btn-xs btn-default' %> |
  <%= link_to 'Back', time_ranges_path, :class => 'btn btn-xs btn-warning' %>
</div>