config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'user_management', to: 'user_management#index'
  get 'user_management/edit/:id', to: 'user_management#edit', as: :user
  patch 'user_management/edit/:id', to: 'user_management#create'
  resources :price_for_advantages
  resources :price_for_reservations
  resources :price_advantages
  resources :reservations
  resources :halls
  resources :time_ranges
  devise_for :users
  get 'home/index'
  root 'home#index'
  get 'halls/:id/reservations', to: 'halls#reservation_form'
  post 'halls/:id/reservations', to: 'halls#reservations'
  get 'my_reservations', to: 'reservations#my_reservations'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservation system for sport center</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar relative: :top, brand: "Reservation system for sport center",  responsive: true do %>
      <% if current_user %>
        <%= menu_group do %>
          <%= menu_item "Home", root_path %>
          <%= menu_item "Halls", halls_path %>
            <% if can? :manage, :null %>
              <%= menu_item "Reservations", reservations_path %>
              <%= menu_item "Price specifications", price_for_reservations_path %>
              <%= menu_item "Price advantages", price_advantages_path %>
              <%= menu_item "Discounts for price specifications", price_for_advantages_path %>
              <%= menu_item "Time ranges", time_ranges_path %>
              <%= menu_item "User management", '/user_management' %>
            <% end %>
          <%= menu_item "My reservations", '/my_reservations' %>
        <% end %>
      <% end %>
      <%= menu_group pull: :right do %>
          <% if current_user %>
              <li><a class="dark-text-in-a"><%= "Logged as #{current_user.username}" %></a></li>
              <%= menu_item "Edit account", '/users/edit' %>
              <%= menu_item "Log Out", destroy_user_session_url, method: :delete %>
          <% end %>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>